print("Welcome to Madlibs")
place = input("Enter a place. ")
person = input("Enter a person. ")
adjective = input("Enter an adjective. ")
noun = input("Enter a noun. ")
pastverb = input("Enter a pastverb. ")
noun1 = input("Enter another noun. ")
adjective1 = input("Enter another adjective. ")
print(f"Today, I went to the {place} with {person}. First, there was a {adjective} {noun}. Afterwards, we {pastverb} at the {noun1}. It was a {adjective1} day!")